agents:
  weather_assistant:
    type: "a2a"
    target_agent_id: "assistant"
    url: "http://localhost:8080/v1/agents/assistant"
  
  concierge:
    reasoning:
      engine: "supervisor"
    llm: "main-llm"
    prompt:
      prompt_slots:
        system_role: |
          You're an concierge assistant that makes suggestions as per the weather conditions.

llms:
  main-llm:
    type: "openai"
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY}"
